spring.application.name=journal_entry
spring.data.mongodb.uri=mongodb+srv://bhadrakishan717_db_user:m7Nur8V5UjHmliNy@cluster0.zf99qqj.mongodb.net/?appName=Cluster0

# mongodb+srv://bhadrakishan717_db_user:m7Nur8V5UjHmliNy@cluster0.zf99qqj.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=Journal_DB
# spring.activemq.user=myJournalUser
# spring.data.mongodb.password=Password
spring.data.mongodb.auto-index-creation=true


