spring.application.name=journal_entry
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=Journal_DB
# spring.activemq.user=myJournalUser
# spring.data.mongodb.password=Password


